name: bemeli_editor
description: A video editor that allows to trim, crop, rotate and scale video with a very flexible UI Design.
version: 0.0.1



environment:
  flutter: ">=3.0.0"
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffmpeg_kit_flutter_min_gpl: ^4.5.1
  path_provider: ^2.0.10
  video_player: 2.2.9
  video_thumbnail: ^0.5.0
  path: ^1.8.0 # update to `1.8.1` causes #79

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1